DEFAULT_DATASET_DIR = "./dataset"

DATASET_TRAIN_DIR = "train"
DATASET_VAL_DIR = "val"
DATASET_TEST_DIR = "test"
DATASET_IMAGES_DIR = "images"
DATASET_TEXTS_DIR = "texts"

DEFAULT_STRING_LEN = 5

DEFAULT_TRAIN_SAMPLES = 1000
DEFAULT_VAL_SAMPLES = 100
DEFAULT_TEST_SAMPLES = 50

ALFABETO = "0123456789"

BORDER_H = 4
BORDER_W = 2